version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: crackly-backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: crackly-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped